### ISSUE TITLE
Allow connection to Navigator server via HTTPS

### ISSUE THREAD

**Issue by KotiM** [cloudera/navigator-sdk#35]
Currently the client is unable to create a connection to Navigator when SSL is enabled due to certificates exceptions.

**Comment by changhiskhan** [comment]
Hi can you provide a little more detail on the error you're running into?

**Comment by changhiskhan** [comment]
I ended up checking this out myself and edited the issue message

**Comment by changhiskhan** [comment]
#41 provides a quick workaround for testing. More to come

**Comment by changhiskhan** [comment]
in case you missed the PR instructions, you need to add "disable_ssl_validation" in your client configuration file for dev/testing.

**Comment by changhiskhan** [comment]
Closed by #41
