### ISSUE TITLE
Support Matrix

### ISSUE THREAD

**Issue by amarouni** [cloudera/navigator-sdk#42]
Do you have a support matrix for the SDK versions vs. Cloudera Navigator version vs. CDH version ?
Is the SDK compatible only with Cloudera Navigator >= 2.4.0 ?

**Comment by changhiskhan** [comment]
The SDK is only compatible with Cloudera Navigator >= 2.4.0

The Navigator support matrix is here: http://www.cloudera.com/content/www/en-us/documentation/enterprise/latest/topics/pcm_navigator.html . Currently CDH 5.4 is the latest release so Navigator 2.4.0 won't appear there for now.

**Comment by changhiskhan** [comment]
@amarouni can I close this issue?

**Comment by amarouni** [comment]
Hello,
Yes you can.
Thanks

Envoyé avec Outlook<http://taps.io/outlookmobile> pour Android



On Tue, Oct 27, 2015 at 10:53 AM -0700, "Chang She" <notifications@github.com<mailto:notifications@github.com>> wrote:


@amarouni<https://github.com/amarouni> can I close this issue?

-
