### ISSUE TITLE
Unable to delete metadata properties

### ISSUE THREAD

**Issue by gokulavasan** [cloudera/navigator-sdk#45]
Hi,

I am using 1.0 version of navigator-sdk-model/client and Navigator 2.4.1. I added a few properties (key-value pairs) to an entity using the client and I was able to see it on the UI. But when I tried to delete a property using the following code, the property (specific key-value pair) didn't get deleted at all. But I am able to delete that property using the UI.

      MyEntity myEntity = new MyEntity(ENTITY_NAME);
      myEntity.removeProperties(Lists.newArrayList(args[1]));
      ResultSet resultSet = navPlugin.write(myEntity);

**Comment by changhiskhan** [comment]
hey gokul, this is going to be the same as removing the tags. I will need to verify this server side for now the entities API is available as workaround. Thanks for your patience

**Comment by changhiskhan** [comment]
As per off-github convo, this has been fixed server side in the upcoming release. Closing this issue for now, can re-open if necessary.
