### ISSUE TITLE
Adding custom field to HiveTable Entity

### ISSUE THREAD

**Issue by manucbilagi** [cloudera/navigator-sdk#63]
Hi Cloudera,

I want to add a custom field of type `**_"INT"_** `to every hive table so that I can later call something like `_**setCustomField(value)**_`
Can you please guide me how it can be done?

**Comment by changhiskhan** [comment]
If you want the values to be int instead of string, you have to create a managed metadata field. This can be done by:
1. extending the existing Hive model
2. Annotate the new field with @MProperty(register=true, fieldType = CustomPropertyType.INTEGER)

Note that this requires Nav-2.6+

**Comment by manucbilagi** [comment]
Thanks for your input. Currently our cluster has Nav - 2.4.4.
