### ISSUE TITLE
Unable to update/add custom properties , tags to Navigator Entities(Hivetable, HDFS..) on Navigator version > 2.9.1 

### ISSUE THREAD

**Issue by avinashr** [cloudera/navigator-sdk#75]
Unable to write the custom properties , tags to Navigator Entities(Hivetable, HDFS..) on Navigator version > 2.9.1 

Below is the sample code that is being used.

 Source hive = client.getSourcesForType(SourceType.HIVE).iterator().next();
        Collection<Source> sourceList = client.getSourcesForType(SourceType.HIVE);
        Collection<Entity> hiveEntityList = new ArrayList<Entity>();

        HiveTable table = new HiveTable();
        table.setDatabaseName("databasename");
        table.setTableName("tablename");
        table.setSourceId(hive.getIdentity());
        table.setSourceType(SourceType.HIVE);
        table.setIdentity(1234);
         table.setTags(tags);
        table.setProperties(properties);
        hiveEntityList.add(table);
        ResultSet results = plugin.write(hiveEntityList);

The call completes successfully but the custom metadata does not showup on the Navigator UI, but the metadata shows up from the API call but as a new entry but is not linked to an existing entity.

**Comment by aadarshjajodia** [comment]
Fixed in v2.0
